title: Braden Tholkes
author: Braden Tholkes
description: Blog of a hiker, and web designer.  Pretty cool guy if you ask me.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
github_username:  btholkes
instagram_username: greekhospitality

# Build settings
markdown: kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate